"""Données du family tree exemple : Famille royale britannique."""

DEMO_FAMILY_TREE = {
    "title": "Famille royale britannique",
    "family_name": "Windsor Mountbatten",
}

# Chaque cell a un "ref" (clé interne) utilisé pour définir les associations.
# Les pictures listées doivent être présentes dans app/demo/pictures/.
DEMO_CELLS = [
    {
        "ref": "elizabeth",
        "name": "Windsor",
        "surnames": "Elizabeth Alexandra Mary",
        "birthday": "21/04/1926",
        "deathday": "08/09/2022",
        "jobs": "Reine du Royaume-Uni de Grande-Bretagne et d'Irlande du Nord et des autres royaumes du Commonwealth",
        "comments": "",
        "generation": -1,
        "pictures": [
            {"filename": "1232e879-678e-4fe8-b9df-212668ffd088.jpg", "header_picture": True},
        ],
    },
    {
        "ref": "philip",
        "name": "Mountbatten",
        "surnames": "Philip",
        "birthday": "10/06/1921",
        "deathday": "09/04/2021",
        "jobs": "",
        "comments": "",
        "generation": -1,
        "pictures": [
            {"filename": "b40b144a-cad3-429c-aed4-88075fe3f667.jpg", "header_picture": True},
            {"filename": "ae0b38e8-2740-4b07-8141-c5e341584c01.jpg", "header_picture": True},
        ],
    },
    {
        "ref": "charles",
        "name": "Mountbatten-Windsor",
        "surnames": "Charles",
        "birthday": "14/11/1948",
        "deathday": None,
        "jobs": "roi",
        "comments": "Charles",
        "generation": 0,
        "pictures": [
            {"filename": "86c24b9a-54c2-4b42-bff4-f9fa3272ff07.jpg", "header_picture": True},
            {"filename": "407a505e-983a-433b-ba74-6f24e287ca25.jpg", "header_picture": True},
        ],
    },
    {
        "ref": "anne",
        "name": "Mountbatten-Windsor",
        "surnames": "Anne Elizabeth Alice Louise",
        "birthday": "15/08/1950",
        "deathday": None,
        "jobs": "Princesse royale",
        "comments": "Princesse du Royaume-Uni",
        "generation": 0,
        "pictures": [
            {"filename": "eba3f3ea-e068-4da6-b81a-724121667682.jpg", "header_picture": True},
        ],
    },
    {
        "ref": "andrew",
        "name": "Mountbatten-Windsor",
        "surnames": "Andrew",
        "birthday": "13/04/1960",
        "deathday": None,
        "jobs": "Duc d'York",
        "comments": "Prince du Royaume-Uni",
        "generation": 0,
        "pictures": [
            {"filename": "8ef4fe5a-4d4c-4418-b07c-75ff27a4d6f4.jpg", "header_picture": True},
        ],
    },
    {
        "ref": "edward",
        "name": "Windsor",
        "surnames": "Edward Antony Richard Louis",
        "birthday": "10/03/1964",
        "deathday": None,
        "jobs": "Duc d'Édimbourg",
        "comments": "Prince du Royaume-Uni",
        "generation": 0,
        "pictures": [
            {"filename": "dd6f3224-2d1b-44f6-b115-b6aa5435c52b.jpg", "header_picture": True},
        ],
    },
    {
        "ref": "diana",
        "name": "Spencer",
        "surnames": "Diana",
        "birthday": "01/07/1961",
        "deathday": "31/08/1997",
        "jobs": "Princesse de Galles",
        "comments": "Princesse de Galles",
        "generation": 0,
        "pictures": [
            {"filename": "dfd07fa1-f2dc-4b88-87f5-d3aad8a480e3.jpg", "header_picture": True},
        ],
    },
    {
        "ref": "camilla",
        "name": "Parker Bowles",
        "surnames": "Camilla",
        "birthday": "17/07/1947",
        "deathday": None,
        "jobs": "Reine consort du Royaume-Uni",
        "comments": "",
        "generation": 0,
        "pictures": [],
    },
    {
        "ref": "william",
        "name": "Mountbatten-Windsor",
        "surnames": "William Arthur Philip Louis",
        "birthday": "21/06/1982",
        "deathday": None,
        "jobs": "Prince de Galles",
        "comments": "",
        "generation": 1,
        "pictures": [
            {"filename": "35ff3d63-18fd-45a1-95bc-b43e39c94a49.jpg", "header_picture": True},
        ],
    },
    {
        "ref": "kate",
        "name": "Middleton",
        "surnames": "Catherine",
        "birthday": "09/01/1982",
        "deathday": None,
        "jobs": "Princesse de Galles",
        "comments": "Kate Middleton",
        "generation": 1,
        "pictures": [
            {"filename": "b2bcc20a-f6b6-47fb-b101-aeeca3864df2.jpg", "header_picture": True},
        ],
    },
    {
        "ref": "harry",
        "name": "Mountbatten-Windsor",
        "surnames": "Henry Charles Albert David",
        "birthday": "15/09/1984",
        "deathday": None,
        "jobs": "Duc de Sussex",
        "comments": "Prince du Royaume-Uni",
        "generation": 1,
        "pictures": [
            {"filename": "56e6f678-1c53-4e9e-b54e-02800006b2b9.jpg", "header_picture": True},
        ],
    },
    {
        "ref": "meghan",
        "name": "Markle",
        "surnames": "Rachel Meghan",
        "birthday": "04/08/1981",
        "deathday": None,
        "jobs": "Actrice, duchesse de Sussex",
        "comments": "Meghan Markle",
        "generation": 1,
        "pictures": [
            {"filename": "5cc249ab-5202-49b8-9d84-62488aaf6e8f.jpg", "header_picture": True},
        ],
    },
    {
        "ref": "george",
        "name": "Mountbatten-Windsor",
        "surnames": "George Alexander Louis",
        "birthday": "22/07/2013",
        "deathday": None,
        "jobs": "",
        "comments": "",
        "generation": 2,
        "pictures": [
            {"filename": "881f2175-884e-4033-b3ce-f37d0a8ab093.jpg", "header_picture": True},
        ],
    },
    {
        "ref": "charlotte",
        "name": "Mountbatten-Windsor",
        "surnames": "Charlotte Elizabeth Diana",
        "birthday": "02/05/2015",
        "deathday": None,
        "jobs": "",
        "comments": "",
        "generation": 2,
        "pictures": [],
    },
    {
        "ref": "louis",
        "name": "Mountbatten-Windsor",
        "surnames": "Louis Arthur Charles",
        "birthday": "23/04/2018",
        "deathday": None,
        "jobs": "",
        "comments": "",
        "generation": 2,
        "pictures": [],
    },
    {
        "ref": "lilibet",
        "name": "de Sussex",
        "surnames": "Lilibet Diana",
        "birthday": "04/06/2021",
        "deathday": None,
        "jobs": "",
        "comments": "",
        "generation": 2,
        "pictures": [],
    },
]

# (parent_ref, child_ref)
DEMO_PARENT_CHILD = [
    ("elizabeth", "charles"),
    ("elizabeth", "anne"),
    ("elizabeth", "andrew"),
    ("elizabeth", "edward"),
    ("philip", "charles"),
    ("philip", "anne"),
    ("philip", "andrew"),
    ("philip", "edward"),
    ("charles", "william"),
    ("diana", "william"),
    ("charles", "harry"),
    ("diana", "harry"),
    ("william", "george"),
    ("kate", "george"),
    ("william", "charlotte"),
    ("kate", "charlotte"),
    ("william", "louis"),
    ("kate", "louis"),
    ("harry", "lilibet"),
    ("meghan", "lilibet"),
]

# (couple_1_ref, couple_2_ref)
DEMO_COUPLES = [
    ("elizabeth", "philip"),
    ("diana", "charles"),
    ("camilla", "charles"),
    ("william", "kate"),
    ("harry", "meghan"),
]

DEMO_PETS = [
    {
        "ref": "sandy",
        "cell_ref": "elizabeth",
        "name": "Sandy",
        "species": "chien",
        "birthday": "02/01/2014",
        "deathday": None,
        "comments": "",
        "picture": "5bd0cbde-0302-45c3-a4bb-ade95e72cb39.jpg",
    },
]
